# Generated by Django 3.0.8 on 2020-08-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('images_choices', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40)),
                ('image_description', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='photos/')),
                ('images', models.ManyToManyField(to='galleria.images')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleria.Location')),
            ],
        ),
    ]
